/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Treasury, TreasuryInterface } from "../Treasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "deposit",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "userBalances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "withdraw",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506103bd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806326224c64146100465780632e1a7d4d14610076578063b6b55f25146100a6575b600080fd5b610060600480360381019061005b91906101e6565b6100d6565b60405161006d91906102a2565b60405180910390f35b610090600480360381019061008b919061020f565b6100ee565b60405161009d9190610280565b60405180910390f35b6100c060048036038101906100bb919061020f565b610133565b6040516100cd9190610280565b60405180910390f35b60006020528060005260406000206000915090505481565b606060006040518060400160405280600681526020017f706c656173650000000000000000000000000000000000000000000000000000815250905080915050919050565b606060008060003073ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff1681526020019081526020016000208190555060006040518060400160405280600681526020017f706c656173650000000000000000000000000000000000000000000000000000815250905080915050919050565b6000813590506101cb81610359565b92915050565b6000813590506101e081610370565b92915050565b6000602082840312156101f857600080fd5b6000610206848285016101bc565b91505092915050565b60006020828403121561022157600080fd5b600061022f848285016101d1565b91505092915050565b6000610243826102bd565b61024d81856102c8565b935061025d818560208601610315565b61026681610348565b840191505092915050565b61027a8161030b565b82525050565b6000602082019050818103600083015261029a8184610238565b905092915050565b60006020820190506102b76000830184610271565b92915050565b600081519050919050565b600082825260208201905092915050565b60006102e4826102eb565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b60005b83811015610333578082015181840152602081019050610318565b83811115610342576000848401525b50505050565b6000601f19601f8301169050919050565b610362816102d9565b811461036d57600080fd5b50565b6103798161030b565b811461038457600080fd5b5056fea2646970667358221220ec4120de4d087c324894791569ac029f33393a4f5b0b2ffe225086e6539298ea64736f6c63430008040033";

export class Treasury__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Treasury> {
    return super.deploy(overrides || {}) as Promise<Treasury>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Treasury {
    return super.attach(address) as Treasury;
  }
  connect(signer: Signer): Treasury__factory {
    return super.connect(signer) as Treasury__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TreasuryInterface {
    return new utils.Interface(_abi) as TreasuryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Treasury {
    return new Contract(address, _abi, signerOrProvider) as Treasury;
  }
}
